### ISSUE TITLE
Fails to ignore pages when using custom build folder

### ISSUE THREAD

**Issue by felipeqq2** [bartholomej/svelte-sitemap#13]
For some reason, this will work:
```
svelte-sitemap -d https://coolwebsite.com -i 404
```

while this won't 😕:
```
svelte-sitemap -d https://coolwebsite.com -o dist -i 404
```

**Comment by bartholomej** [comment]
Thanks @felipeqq2!

In this pull request #14 you can see I just fixed this issue and also added tests for more combinations. And there is a new separate test pass just for outDir to make sure there is not another bug 🙏 :) 

Lets try version `v2.1.0` and let me know how it works ;)

**Comment by felipeqq2** [comment]
Everything ok now!
