### ISSUE TITLE
`npm run svelte-sitemap --domain https://example.com` doesn't work

### ISSUE THREAD

**Issue by tarasinf** [bartholomej/svelte-sitemap#18]
`npm run svelte-sitemap --domain https://example.com` doesn't work, output:
```
npm ERR! Missing script: "svelte-sitemap"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

I want to use as a post build hook, but need this command to test it locally. I used option with file, from [example](https://github.com/bartholomej/svelte-sitemap#typescript-or-javascript-method-optional), that works well. would be good to fix it.

**Comment by bartholomej** [comment]
Hey @tarasinf, you're right, the documentation was a little misleading. 
If you use `npm`, then you can run the script via `npx` for example.

Try it and let me know. I will change the documentation as well.

```bash
{
  "name": "my-project",
  "scripts": {
    "postbuild": "npx svelte-sitemap --domain https://mydomain.com"
  }
}
```

or with yarn just use `yarn svelte-sitemap --domain https://mydomain.com`

Thanks ;)

**Comment by bartholomej** [comment]
I believe now it is more clear so I closing this issue.
Feel free to comment afterwards.
