### ISSUE TITLE
SvelteKit new default adapter-static configuration makes Sitemap point to invalid URL

### ISSUE THREAD

**Issue by matfantinel** [bartholomej/svelte-sitemap#24]
Hello!

So, after [this PR](https://github.com/sveltejs/kit/pull/3801) was merged, my static website started building pages in the folder like `/my-page.html` instead of `/my-page/index.html`. This works fine on the hosting side, but I've found that the Sitemap is now generated with the ".html" in the end of the URL. However, that URL is invalid as it will throw a 404.

Sample generated sitemap:

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- This file was automatically generated by https://github.com/bartholomej/svelte-sitemap v2.3.0 -->
  <url>
    <loc>https://fantinel.dev/2019-year-in-review.html</loc>
  </url>
  <url>
    <loc>https://fantinel.dev/2020-year-in-review.html</loc>
  </url>
</urlset>
```

The project I use it on is this: https://github.com/matfantinel/matfantinel.github.io
You can currently reproduce it on main branch by running `npm run build`.

I'm using svelte-sitemap v2.3.0. Happy to offer more details if needed

**Comment by bartholomej** [comment]
Hi Matt,
that's exactly [the line in your repository](https://github.com/matfantinel/matfantinel.github.io/commit/eac93834357b9a62eb4bc67f8396d125dd4ccbe5#diff-6317e218ea40a2a9b47af98e100e81c06f9c0abff66737e6ca06ec4b29402242R42) which will solve everything :)

I also recommend setting the following in the svelte-sitemap config.
--trailing-slashes true
Then the trailing slashes in sitemap.xml will match the new svelte folder structure.

**Comment by matfantinel** [comment]
Hi @bartholomej ! Yep, that seems to have solved the issue on my repo. Still, I guess it would make sense for svelte-sitemap to remove the .html from the URL since that is now the default behavior?

I'll check the `--trailing-slashes` flag too, thank you! 😄

**Comment by bartholomej** [comment]
Yes you're right @matfantinel 
Version `2.4.0` has just been released, and should fix this problem.

This means that it should be compatible with the old Sveltekit version and should not depend on the new svelte `trailing slashes` option.

Can you please try it? ;)

**Comment by matfantinel** [comment]
@bartholomej yup, it seems to have fixed it!

I ended up always using trailing slashes on my project since it seems to get more consistent results in my web analytics this way; but that release makes it work on the default settings again!

Thank you! 😊
