### ISSUE TITLE
Parameter -t does not work

### ISSUE THREAD

**Issue by Meldiron** [bartholomej/svelte-sitemap#28]
Hey there 👋 I have tried this project for my small Svelte Kit website and found a tiny documentation or code bug.

Docs state:

<img width="901" alt="CleanShot 2022-05-28 at 11 11 39@2x" src="https://user-images.githubusercontent.com/19310830/170819016-3f6ab77f-7bea-41e9-81fb-de6575be872e.png">

But command results in following:

```sh
> npx svelte-sitemap -t --domain https://#####/

⚠ Those arguments are not supported: -t
Use: `svelte-sitemap --help` for more options.
```

I think the solution is simply to add a new alias to the list:

https://github.com/bartholomej/svelte-sitemap/blob/master/index.ts#L16-L31

Let me know if the project is open to contributions and I will gladly submit a PR 😇

**Comment by bartholomej** [comment]
Hi @Meldiron you are absolutely right. Thank you!
Of course this project is open for contributions and improvements.
I look forward to you pull request ;)
