### ISSUE TITLE
Custom build dir

### ISSUE THREAD

**Issue by bartholomej** [bartholomej/svelte-sitemap#3]
> I am using the vercel adapter with its own build output folder. Would be great if we can customize the build dir.

– Originally requested by @tonprince in this issue https://github.com/bartholomej/svelte-sitemap/issues/1#issuecomment-873361137

**Comment by bartholomej** [comment]
@tonprince 
I made a new option for that and I called it `outDir` and `--out-dir` respectively.
It is inspired by ts-config.json nomenclature.

Install: _(v1.2.0-beta.0)_
```
npm install svelte-sitemap@next
```


Usage:
```
{
  "name": "my-project",
  "scripts": {
    "postbuild": "svelte-sitemap --domain https://mydomain.com --out-dir my-custom-build-folder"
  }
}
```

Let me know what do you think ;)

**Comment by tonprince** [comment]
Thanks, that looks great.

**Comment by bartholomej** [comment]
@tonprince @100lvlmaster 
Stable version v1.2.1 just released

Thanks guys ;)
```
npm install svelte-sitemap --save-dev
```
