### ISSUE TITLE
Small script changes needed for SvelteKit 1.0 on Vercel using adapter-static

### ISSUE THREAD

**Issue by lakebayagency** [bartholomej/svelte-sitemap#31]
Hi,

Just wanted to document here that the correct (AFAIK - it works for me!) script in package.json for a Vercel deployment is:

npx svelte-sitemap --out-dir **.vercel/output/static** --domain https://www.example.com

**Comment by bartholomej** [comment]
Thanks, I've added it to the documentation ;)
