### ISSUE TITLE
Large Sites

### ISSUE THREAD

**Issue by eecue** [bartholomej/svelte-sitemap#32]
Hello, great tool, one problem though, sitemaps are limited to 50k entries per page.

**Comment by eecue** [comment]
I made a PR: https://github.com/bartholomej/svelte-sitemap/pull/33

**Comment by eecue** [comment]
Hmm also needs an index:

https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps

**Comment by bartholomej** [comment]
Great idea, Dave! 
And yes, sitemap index is needed when you split into chunks, but it won't be complicated.
I will take a look.

**Comment by bartholomej** [comment]
Yes, your PR is great!

So now we just need to do this: 
- [ ] create sitemap index as well
- [ ] write tests for this new feature
- [ ] we must not make any breaking changes for smaller sites (I think there will be missing sitemap.xml file in build now)
- [ ] improve CLI logs that are displayed during sitemap build

I'll use your codebase and let you know ;)

**Comment by bartholomej** [comment]
Check this: https://github.com/bartholomej/svelte-sitemap/compare/large-sitemaps

I'll make a special release for you tomorrow. I'd appreciate some test on your real website.

**Comment by eecue** [comment]
Awesome! I’m ready to test!

**Comment by bartholomej** [comment]
So try version `2.6.0-beta.1` and let me know ;)
```bash
npm i svelte-sitemap@beta --save 
```

**Comment by eecue** [comment]
Perfect!

**Comment by bartholomej** [comment]
@eecue Please let me know if it works in your real environment and if all files are valid.
You can use some of [online validators](https://www.xml-sitemaps.com/validate-xml-sitemap.html)

**Comment by eecue** [comment]
Yep I did and it's valid!
