### ISSUE TITLE
Consider filtering out 404 

### ISSUE THREAD

**Issue by jasongitmail** [bartholomej/svelte-sitemap#38]
I noticed my sitemap.xml contains a /404 route. It might be worth filtering that out of the final result.

To repro:
I used the cloudflare-adapter (steps detailed in my other issue), and all worked as expected, afaict.

**Comment by bartholomej** [comment]
Thanks! Have you tried the `--ignore` parameter?
See more here:
https://github.com/bartholomej/svelte-sitemap?tab=readme-ov-file#%EF%B8%8F-options

**Comment by jasongitmail** [comment]
Appreciate the response. 🙏

I ended up (not because of this GitHub issue) building an alternative package bc I wanted something that supports routes using any rendering method (not just static), parameterized routes, sitemap indexes, i18n, has checks to ensure no routes are accidentally omitted by the dev, etc. 

Goal is to create a thorough solution for the ecosystem as my way to give back to the svelte community. It's actively maintained. Give it a look https://github.com/jasongitmail/super-sitemap

**Comment by jasongitmail** [comment]
For this issue, I'd suggest nobody will want a 404 in their sjtemap so it should be excluded by default for a good DX. That was the reason for creating the issue
