### ISSUE TITLE
Exclude pages from sitemap

### ISSUE THREAD

**Issue by weaseldotro** [bartholomej/svelte-sitemap#6]
First of all, thank you very much for this project and your work, I use it in my project and it's great!

Second, is there any way to exclude certain pages from the sitemap? For example, auth pages or maybe "secret" pages that you don't want to be indexed?

**Comment by bartholomej** [comment]
@weaseldotro Good point ;) `v1.6.0` will be for you ;) 

Install this version:
```bash
npm install svelte-sitemap@v1.6.0-next.0
```

And this is how to use it: https://github.com/bartholomej/svelte-sitemap/tree/exclude#how-to-exclude-directory

```bash
svelte-sitemap --domain https://www.example.com --ignore 'pages/my-secret-page' --ignore '**/admin/**'
```

Let me know how it works ;)

**Comment by weaseldotro** [comment]
You are a wonderful person 😊

**Comment by weaseldotro** [comment]
Works great, thanks a bunch!

One thing I noticed is that the previous version would not append a trailing slash at the end of the URLs, but this version does that. I would prefer it without a trailing slash, perhaps this could also be a command line option so the developer would use the variant they want?

**Comment by bartholomej** [comment]
Hi @weaseldotro 
I don't think this change affected the trailing slashes. They have been in the [tests](https://github.com/bartholomej/svelte-sitemap/blob/master/tests/main.test.ts) from the very beginning.
But yes, I can easily add this option. 

However, this is for a new issue. Feel free to create it ;)
