### ISSUE TITLE
Make "This file was automatically generated..." text optional

### ISSUE THREAD

**Issue by gavinr** [bartholomej/svelte-sitemap#7]
For security reasons we may not want to share what technology is being used to generate the site.

Add a `no-attribution` switch to be used like: `svelte-sitemap --domain https://stlouis.closedparishes.com --no-attribution`

Which will stop this line from being run: https://github.com/bartholomej/svelte-sitemap/blob/ab8f29461a38ed1ad709789551d39103d173384b/src/helpers/global.helper.ts#L35-L37

**Comment by bartholomej** [comment]
@gavinr I think you will like `v1.5.0`, which does **exactly** what you want ;)

BTW: If this is all for security reasons, then you probably shouldn't write the url of your website in this issue ;)

**Comment by gavinr** [comment]
Thank you very much!
