### ISSUE TITLE
Add option for including or excluding trailing slashes in the sitemap

### ISSUE THREAD

**Issue by weaseldotro** [bartholomej/svelte-sitemap#9]
Continuing from https://github.com/bartholomej/svelte-sitemap/issues/6#issuecomment-898338813

Perhaps you could add a command line argument where you can specify whether the URLs in the sitemap should contain a trailing slash or not.
It's up to you which should be the default, if it were my call I would not include a trailing slash by default and expect the developer to specify that they want this option.

Thanks again for your work on this project, I really appreciate it.

**Comment by bartholomej** [comment]
@weaseldotro And here we are!

I decided the default option would be without trailing slashes, as I use it everywhere.
This is a potential breaking change, so I'm bumping to version `v2.0.0`

Install this version `v2.0.0-next.0`

```bash
npm install svelte-sitemap@v2.0.0-next.0
```

And use it (default option is `false`)
```bash
svelte-sitemap --domain https://www.example.com --trailing-slashes
```

Let me know how it works. Please try both option in your setup ;)

**Comment by weaseldotro** [comment]
Works great, I am using it without the trailing slashes, I think it looks cleaner.
